/**
 * Generated by orval v6.18.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface CreateBannedRangeDTO {
  scheduleStartTime?: string;
  scheduleEndTime?: string;
}
