/**
 * Generated by orval v6.18.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { CreateTaskDTOPriority } from './createTaskDTOPriority';

export interface CreateTaskDTO {
  name: string;
  startDay?: string | null;
  startTime?: string | null;
  durationMin?: number | null;
  priority?: CreateTaskDTOPriority;
  projectId?: string | null;
}
