/**
 * Generated by orval v6.18.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Link } from './link';

export type Links200One = {[key: string]: {[key: string]: Link}};
