/**
 * Generated by orval v6.18.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface ProjectDTO {
  id?: string;
  name: string;
  scheduleStartTime?: string;
  scheduleEndTime?: string;
  color?: string | null;
}
