/**
 * Generated by orval v6.18.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface TaskDTO {
  id?: string;
  name?: string;
  startDate?: string;
  startTime?: string;
  durationMin?: number;
}
