/**
 * Generated by orval v6.18.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface TaskDTO {
  id?: string;
  name: string;
  startDay?: string | null;
  startTime?: string | null;
  durationMin?: number | null;
  isImportant?: boolean;
  isUrgent?: boolean;
  projectId?: string;
}
