/**
 * Generated by orval v6.18.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type TaskDTOPriority = typeof TaskDTOPriority[keyof typeof TaskDTOPriority];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TaskDTOPriority = {
  IMPORTANT_URGENT: 'IMPORTANT_URGENT',
  IMPORTANT: 'IMPORTANT',
  URGENT: 'URGENT',
  NORMAL: 'NORMAL',
} as const;
