/**
 * Generated by orval v6.18.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UpdateTaskDTOPriority } from './updateTaskDTOPriority';

export interface UpdateTaskDTO {
  name?: string;
  startDay?: string | null;
  startTime?: string | null;
  durationMin?: number | null;
  priority?: UpdateTaskDTOPriority;
  projectId?: string | null;
}
