/**
 * Generated by orval v6.18.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface UpdateTaskDTO {
  name?: string;
  startDay?: string | null;
  startTime?: string | null;
  durationMin?: number | null;
  isImportant?: boolean | null;
  isUrgent?: boolean | null;
  projectId?: string | null;
}
