/**
 * Generated by orval v6.18.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type UpdateTaskDTOPriority = typeof UpdateTaskDTOPriority[keyof typeof UpdateTaskDTOPriority];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateTaskDTOPriority = {
  IMPORTANT_URGENT: 'IMPORTANT_URGENT',
  IMPORTANT: 'IMPORTANT',
  URGENT: 'URGENT',
  NORMAL: 'NORMAL',
  null: null,
} as const;
